test: update test for both ngx_lua_module and stream_ngx_lua_module
openresty/lua-resty-mysql pull request #115
Opened 2020-10-29 02:56 UTC by rainingmaster

2020-10-29 13:48 UTC, xiaocang requested changes

2020-10-29 13:48 UTC, xiaocang commented on t/Test.pm
> +    if ($ENV{TEST_SUBSYSTEM} eq "stream") {
You should first determine if the environment variable exists.

2020-10-29 13:48 UTC, xiaocang commented on t/Test.pm
> +            $block->set_value("request", <<'_END_');
Just quotes here, very short string.

2020-10-29 13:48 UTC, xiaocang commented on t/Test.pm
> +            $block->set_value("config", "location /t {\n" . $block->server_config . "\n}");
Consider using heredoc with multiple rows of string.

2020-10-29 13:48 UTC, xiaocang commented on t/big.t
> +use t::Test;
you forgot `@skip` variable here.

2020-10-29 13:48 UTC, xiaocang commented on t/Test.pm
> +            $block->set_value("stream_config", $block->global_config);
Why introduce a new `block->global_config` here, while repeating it in every test block.
If you just use it as a default value of `stream_config` or `http_config`, just use the local variable if `stream_config` or `http_config` doesn't exist. (and you don't need a global variable)

2020-10-29 13:57 UTC, xiaocang commented
PR title here shoud be `tests: ...` not `test: ...` according to http://openresty.org/en/git-workflow.html.

2020-10-30 04:38 UTC, xiaocang commented on t/Test.pm
> +our $GlobalConfig = qq{
You don't need a global variable (`$GlobalConfig`) and export it anymore, just use a local variable like `my $default_config` is enough.

2020-10-31 02:54 UTC, xiaocang approved these changes

2020-10-31 03:27 UTC, rainingmaster commented
Thanks @xiaocang

2020-11-02 02:07 UTC, merged